version: "2"
services:
  taavoni:
    container_name: taavoni_app
    image: taavoni_app:latest
    build:
      context: .
      # args: 
      #   - SREVER_PORT=3000
      #   - DB_PORT=2018
      #   - DB_URI='mongodb://taavoni_mongodb:27018/TaavoniDb'
    environment:
        - ENV_TAV_SERVER_PORT=3000
        - ENV_TAV_DB_URI=mongodb://taavoni_mongodb:27020/TaavoniDb
    ports:
        - "3000:3000"
    links:
        - mongo:taavoni_mongodb
  mongo:
    container_name: taavoni_mongodb
    image: mongo:latest
    command: mongod --port 27020
    ports:
      - "27020:27020"

# ---- docker-compose command ----
# docker-compose up
# docker-compose rebuild
