version: "2"
services:
  taavoni:
    container_name: taavoni_app
    build:
      context: .
      args: 
        SREVER_PORT:3000
        DB_PORT:2017
        DB_URI:'mongodb://taavoni_mongodb:${DB_PORT}/TaavoniDb'
      environment:
        - ENV_TAV_SERVER_PORT=${SREVER_PORT}
        - ENV_TAV_DB_URI=${DB_URI}
      ports:
        - "${SREVER_PORT}:${SREVER_PORT}"
      links:
        - mongo:taavoni_mongodb
  mongo:
    container_name: taavoni_mongodb
    image: mongo:latest
    ports:
      - "27017:${DB_PORT}"

# ---- docker-compose command ----
# docker-compose up
# docker-compose rebuild
